server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /user-service
spring:
  application:
    name: user-service
  datasource:
    url: ${POSTGRES_URL}/user_service
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    url: ${POSTGRES_URL}/user_service
    schemas: public
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION_TIME}