server:
  port: 5000
spring:
  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  flyway:
    url: ${RDS_URL}
    user: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
eureka:
  client:
    service-url:
      defaultZone: http://awseb-awseb-13vv4savxy5co-1660512157.eu-central-1.elb.amazonaws.com/eureka