server:
  port: 8082
  servlet:
    context-path: /user-service
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    url: jdbc:postgresql://localhost:5432/user_service
    schemas: public
    user: postgres
    password: postgres
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
jwt:
  secret: bezKoderSecretKey
  expiration: 86400000