server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /user-service
spring:
  application:
    name: user-service
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    url: ${POSTGRES_URL}
    schemas: public
    user: ${POSTGRES_USERNAME}
    password: ${POSTGRES_USERNAME}
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
aws:
  access-key-id: ${S3_ACCESS_KEY_ID}
  secret-access-key: ${S3_SECRET_ACCESS_KEY}
  s3:
    region: eu-central-1
    bucket-name: ${S3_BUCKET_NAME}
    profile-pictures-folder: user-service/profile-pictures/